version: '3.1'
services:
    node:
        build: "."
        links:
            - db
        depends_on:
            - db
        networks:
            - wpsite
        ports:
          - "7000:7000"
        volumes:
            - ./:/usr/app/
            - /usr/app/node_modules
        command: npm start
    db:
        image: mysql:5.7
        volumes:
          - mysql:/var/lib/mysql
          - ./docker/dbdata:/docker-entrypoint-initdb.d/
        restart: always
        environment:
          MYSQL_DATABASE: db
          MYSQL_ROOT_PASSWORD: root
        networks:
          - wpsite
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
            UPLOAD_LIMIT: 100000000000
        networks:
            - wpsite
volumes:
    mysql:
networks:
    wpsite: