version: '3.1'
services:
    node:
        links:
            - db
        depends_on:
            - db
        build: ./
        networks:
            - wpsite
        ports:
          - "7000:7000"
        volumes:
            - ./:/app
    db:
        image: mariadb:10.3
        networks:
            - wpsite
        restart: always
        volumes:
            - mariadb:/var/lib/mysql
            - ./docker/dbdata:/docker-entrypoint-initdb.d/
        environment:
            MYSQL_DATABASE: db
            MYSQL_ROOT_PASSWORD: root
    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - '8080:80'
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: root
            UPLOAD_LIMIT: 100000000000
        networks:
            - wpsite
volumes:
    mysql:
    mariadb:
networks:
    wpsite: